[project]
name = "zap_test_settez"
version = "0.5.0"
description = "a 'zap'"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["zap_test_settez"]
